// mock.ts — Mock Solari primitives for offline / CI / no-key runs.
// All methods are promise-based, log with [mock] prefix, and return
// plausible fake data so examples render without a real SOLARI_API_KEY.

export class MockPage {
  url: string | null = null;

  async goto(url: string): Promise<void> {
    this.url = url;
    console.log(`[mock] MockPage.goto(${url})`);
  }

  async title(): Promise<string> {
    console.log("[mock] MockPage.title()");
    return "Chow on Solari — Mock Page";
  }

  locator(selector: string) {
    console.log(`[mock] MockPage.locator(${selector})`);
    return {
      innerText: async (): Promise<string> => {
        console.log(`[mock] locator("${selector}").innerText()`);
        return `Mock content for ${selector}`;
      },
      click: async (): Promise<void> => {
        console.log(`[mock] locator("${selector}").click()`);
      },
      waitFor: async (): Promise<void> => {
        console.log(`[mock] locator("${selector}").waitFor()`);
      },
    };
  }

  async screenshot(opts?: { fullPage?: boolean }): Promise<Buffer> {
    console.log(`[mock] MockPage.screenshot(${JSON.stringify(opts ?? {})})`);
    // 1x1 transparent PNG
    return Buffer.from(
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=",
      "base64",
    );
  }

  async content(): Promise<string> {
    console.log("[mock] MockPage.content()");
    return "<html><body><h1>Chow on Solari — mock render</h1></body></html>";
  }

  async close(): Promise<void> {
    console.log("[mock] MockPage.close()");
  }
}

export class MockBrowser {
  id = "mock-session";
  private _pages: MockPage[] = [];

  async newPage(): Promise<MockPage> {
    console.log("[mock] MockBrowser.newPage()");
    const page = new MockPage();
    this._pages.push(page);
    return page;
  }

  async close(): Promise<void> {
    console.log("[mock] MockBrowser.close()");
  }

  // Playwright-compatible alias some examples use
  get pages(): MockPage[] {
    return this._pages;
  }
}

export class MockSandbox {
  id = "mock-sandbox";

  commands = {
    run: async (
      cmd: string,
      opts?: { args?: string[] },
    ): Promise<{ stdout: string; stderr: string; exitCode: number }> => {
      const full = [cmd, ...(opts?.args ?? [])].join(" ");
      console.log(`[mock] MockSandbox.commands.run(${JSON.stringify(full)})`);
      return {
        stdout: `[mock] ran: ${full}\nhello from sandbox`,
        stderr: "",
        exitCode: 0,
      };
    },
  };

  files = {
    write: async (path: string, content: string): Promise<void> => {
      console.log(`[mock] MockSandbox.files.write(${path}, ${content.length} bytes)`);
    },
    readText: async (path: string): Promise<string> => {
      console.log(`[mock] MockSandbox.files.readText(${path})`);
      return `# mock file: ${path}\n# generated by chow-solari mock`;
    },
    read: async (path: string): Promise<Buffer> => {
      console.log(`[mock] MockSandbox.files.read(${path})`);
      return Buffer.from(`mock file: ${path}`);
    },
  };

  async kill(): Promise<void> {
    console.log("[mock] MockSandbox.kill()");
  }
}

export class MockDesktop {
  id = "mock-desktop";
  streamUrl = "http://localhost:7900/mock-vnc";

  async health(): Promise<{ status: string; uptimeMs: number }> {
    console.log("[mock] MockDesktop.health()");
    return { status: "ok", uptimeMs: 1234 };
  }

  async screenshot(): Promise<Buffer> {
    console.log("[mock] MockDesktop.screenshot()");
    return Buffer.from(
      "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=",
      "base64",
    );
  }

  mouse = {
    move: async (x: number, y: number): Promise<void> => {
      console.log(`[mock] MockDesktop.mouse.move(${x}, ${y})`);
    },
    click: async (x: number, y: number): Promise<void> => {
      console.log(`[mock] MockDesktop.mouse.click(${x}, ${y})`);
    },
    humanize: async (x: number, y: number): Promise<void> => {
      console.log(`[mock] MockDesktop.mouse.humanize(${x}, ${y})`);
    },
  };

  keyboard = {
    type: async (text: string): Promise<void> => {
      console.log(`[mock] MockDesktop.keyboard.type(${JSON.stringify(text)})`);
    },
    press: async (key: string): Promise<void> => {
      console.log(`[mock] MockDesktop.keyboard.press(${key})`);
    },
  };

  async open(app: string): Promise<void> {
    console.log(`[mock] MockDesktop.open(${app})`);
  }

  async close(): Promise<void> {
    console.log("[mock] MockDesktop.close()");
  }

  async destroy(): Promise<void> {
    console.log("[mock] MockDesktop.destroy()");
  }
}

// Convenience factories used by index.ts when in mock mode
export function createMockBrowser(): MockBrowser {
  console.log("[mock] createMockBrowser() -> { id: mock-session }");
  return new MockBrowser();
}

export function createMockSandbox(): MockSandbox {
  console.log("[mock] createMockSandbox() -> { id: mock-sandbox }");
  return new MockSandbox();
}

export function createMockDesktop(): MockDesktop {
  console.log("[mock] createMockDesktop() -> { id: mock-desktop }");
  return new MockDesktop();
}
